var contents = [
'<img src="assets/img/logo_sfvn.png" class="s-logo" /> <label class="s-lft-5">Salary: $300 - $1000 USD</label><br /><br /><b>System Integration Engineer</b><br />Address: 5th Floor, 215 Nam Ky Khoi Nghia Street, Ward 7, District 3, HCMC <br />Phone: 0908977273 (Mr. Sang) <br />Email: sang.truong@softfront.com<br />Distance: 20km<br /><a href="http://www.vietnamworks.com/system-integration-engineer-working-in-ha-noi-610177-jd">View Details</a>',
'<img src="assets/img/logo_el.png" class="s-logo" /> <label class="s-lft-5">Salary: Negotiable</label><br /><br /><b>Java Developer</b><br />Address: 4F Saigon Finance Center, No. 9 Dinh Tien Hoang St., Dist 1, HCMC <br />Phone: 0903477273 (Mr. Hai) <br />Email: hai.truong@evolable.com<br />Distance: 10km<br /><a href="http://www.vietnamworks.com/urgent-java-developer-luong-canh-tranh-3-609712-jd">View Details</a>',
'<img src="assets/img/logo_elca.png" class="s-logo" /> <label class="s-lft-5">Salary: 1000-2000 USD</label><br /><br /><b>Front-end Developers</b><br />Address: Melody-2 Tower, N1 Dien Bien Phu, Ward 25, Binh Thanh District <br />Phone: 0903477253 (Mr. A) <br />Email: A.truong@elca.com<br />Distance: 15km<br /><a href="http://www.vietnamworks.com/front-end-developers-3-613855-jd">View Details</a>',
'<img src="assets/img/logo.png" class="s-logo" /> <label class="s-lft-5">Salary: 2000-4000 USD</label><br /><br /><b>Front-end Developers</b><br />Address: 30 Suong Nguyet Anh Street, Ben Thanh Ward, District 1, Ho Chi Minh City, Vietnam <br />Phone: 0903477253 (Mr. B) <br />Email: B.truong@vietnamwork.com<br />Distance: 5km<br /><a href="http://www.vietnamworks.com/front-end-developers-3-613855-jd">View Details</a>',
'<img src="assets/img/logo_s3.jpg" class="s-logo" /> <label class="s-lft-5">Salary: 800-1000 USD</label><br /><br /><b>Front-end Developers</b><br />Address: Ho Chi Minh, Tan Binh District, Nguyễn Văn Trỗi  <br />Phone: 0903477253 (Mr. C) <br />Email: C.truong@s3.com<br />Distance: 4km<br /><a href="http://www.vietnamworks.com/">View Details</a>',
'<img src="assets/img/logo_vmax.png" class="s-logo" /> <label class="s-lft-5">Salary: 1000-2000 USD</label><br /><br /><b>Senior Web Developer</b><br />Address: 18A/76 Nguyễn Thị Minh Khai, P.Đakao, Q.1 <br />Phone: 0903477253 (Mr. D) <br />Email: D.truong@vmax.com<br />Distance: 5km<br /><a href="http://www.vietnamworks.com/senior-php-developer-800-1000-614854-jd">View Details</a>',
'<img src="assets/img/logo_brv.png" class="s-logo" /> <label class="s-lft-5">Salary: 400-1000 USD</label><br /><br /><b>Php, iOS Developer (urgent)</b><br />Address: 2F-C3 Mirae Building, 268 To Hien Thanh Street, Ward 15, District 10, Ho Chi Minh City <br />Phone: 0903477253 (Mr. E) <br />Email: E.truong@brv.com<br />Distance: 6km<br /><a href="http://www.vietnamworks.com/senior-web-developer-24-613489-jd">View Details</a>',
'<img src="assets/img/logo_jvit.jpg" class="s-logo" /> <label class="s-lft-5">Salary: $800 - $1000 USD</label><br /><br /><b>Tuyển Leader iOS, Android Leader (gấp)</b><br />Address: 115-115A Võ Văn Tần, phường 6, Quận 3, TP.HCM <br />Phone: 0903477253 (Mr. F) <br />Email: F.truong@jvit.com<br />Distance: 23km<br /><a href="http://www.vietnamworks.com/php-ios-developer-urgent-613191-jd">View Details</a>',
'<img src="assets/img/logo_gl.png" class="s-logo" /> <label class="s-lft-5">Salary: Negotiable</label><br /><br /><b>PHP Programmer</b><br />Address: 7th Floor, E-Town 2, 364 Cong Hoa <br />Phone: 0903477253 (Mr. G) <br />Email: G.truong@gl.com<br />Distance: 12km<br /><a href="http://www.vietnamworks.com/tuyen-leader-ios-android-leader-gap-612159-jd">View Details</a>',
'<img src="assets/img/logo_ag.jpg" class="s-logo" /> <label class="s-lft-5">Salary: Negotiable</label><br /><br /><b>System Engineer</b><br />Address: 25th Floor, Lim Tower, 9-11 Ton Duc Thang, Ben Nghe Ward, District 1, Ho Chi Minh City <br />Phone: 0903477253 (Mr. H) <br />Email: H.truong@ag.com<br />Distance: 7km<br /><a href="http://www.vietnamworks.com/php-programmer-7-1-610882-jd">View Details</a>',
]; 